package com.bibfortuna.powerconverters;

public enum Planet
{
    //Special planet for the origin of things that don't have a real planetary origin, like Bocce or Binary
    UTILITY(SpaceRegion.DEEPCORE),

    //Deep Core 3 total
    BYSS(SpaceRegion.DEEPCORE),
    ECLIPSE(SpaceRegion.DEEPCORE),
    KHOMM(SpaceRegion.DEEPCORE),

    //Core Worlds 17 total
    ALDERAAN(SpaceRegion.COREWORLDS),
    ABREGADO_RAE(SpaceRegion.COREWORLDS),
    BRENTAAL(SpaceRegion.COREWORLDS),
    CAAMAS(SpaceRegion.COREWORLDS),
    CORELLIA(SpaceRegion.COREWORLDS),
    CORUSCANT(SpaceRegion.COREWORLDS),
    DURO(SpaceRegion.COREWORLDS),
    EMPRESS_TETA(SpaceRegion.COREWORLDS),
    FROZ(SpaceRegion.COREWORLDS),
    GALANTOS(SpaceRegion.COREWORLDS),
    JUMUS(SpaceRegion.COREWORLDS),
    KUAT(SpaceRegion.COREWORLDS),
    NEW_PLYMPTO(SpaceRegion.COREWORLDS),
    N_ZOTH(SpaceRegion.COREWORLDS),
    RUAN(SpaceRegion.COREWORLDS),
    SACORRIA(SpaceRegion.COREWORLDS),
    TALFAGLIO(SpaceRegion.COREWORLDS),

    //Colonies 11 total
    ANTAR(SpaceRegion.COLONIES),
    ARKANIA(SpaceRegion.COLONIES),
    BALMORRA(SpaceRegion.COLONIES),
    BORLEIAS(SpaceRegion.COLONIES),
    COMMENOR(SpaceRegion.COLONIES),
    FONDOR(SpaceRegion.COLONIES),
    NEIMOIDIA(SpaceRegion.COLONIES),
    NUBIA(SpaceRegion.COLONIES),
    ONDERON(SpaceRegion.COLONIES),
    PHU(SpaceRegion.COLONIES),
    TEYR(SpaceRegion.COLONIES),

    //Inner Rim 15 total
    ALEEN(SpaceRegion.INNERRIM),
    AMBRIA(SpaceRegion.INNERRIM),
    ATZERRI(SpaceRegion.INNERRIM),
    BESTINE(SpaceRegion.INNERRIM),
    BILBRINGI(SpaceRegion.INNERRIM),
    CARRATOS(SpaceRegion.INNERRIM),
    HAPES_CONSORTIUM(SpaceRegion.INNERRIM),
    MOORJA(SpaceRegion.INNERRIM),
    MYRKR(SpaceRegion.INNERRIM),
    OBROA_SKAI(SpaceRegion.INNERRIM),
    REECEE(SpaceRegion.INNERRIM),
    TANAAB(SpaceRegion.INNERRIM),
    TELTI(SpaceRegion.INNERRIM),
    THYFERRA(SpaceRegion.INNERRIM),
    YAG_DHUL(SpaceRegion.INNERRIM),

    //Expansion 13 total
    AQUARIS(SpaceRegion.EXPANSION),
    ARIDUS(SpaceRegion.EXPANSION),
    DORIN(SpaceRegion.EXPANSION),
    GYNDINE(SpaceRegion.EXPANSION),
    IKTOTCH(SpaceRegion.EXPANSION),
    MALASTARE(SpaceRegion.EXPANSION),
    M_HAELI(SpaceRegion.EXPANSION),
    MIMBAN(SpaceRegion.EXPANSION),
    NKLLON(SpaceRegion.EXPANSION),
    OSARIAN(SpaceRegion.EXPANSION),
    PLOO(SpaceRegion.EXPANSION),
    RHOMMAMOOL(SpaceRegion.EXPANSION),
    SHILI(SpaceRegion.EXPANSION),
    TYNNA(SpaceRegion.EXPANSION),

    //Mid Rim 32 total
    ANDO(SpaceRegion.MIDRIM),
    ANOBIS(SpaceRegion.MIDRIM),
    ANSION(SpaceRegion.MIDRIM),
    BELSAVIS(SpaceRegion.MIDRIM),
    BIMMISAARI(SpaceRegion.MIDRIM),
    BOTHAWUI(SpaceRegion.MIDRIM),
    CEREA(SpaceRegion.MIDRIM),
    CHALACTA(SpaceRegion.MIDRIM),
    CULARIN(SpaceRegion.MIDRIM),
    TRANDOSHA(SpaceRegion.MIDRIM),
    DRUCKENWELL(SpaceRegion.MIDRIM),
    FALLEEN(SpaceRegion.MIDRIM),
    GAROS_IV(SpaceRegion.MIDRIM),
    IRIDONIA(SpaceRegion.MIDRIM),
    ITHOR(SpaceRegion.MIDRIM),
    KALARBA(SpaceRegion.MIDRIM),
    KASHYYYK(SpaceRegion.MIDRIM),
    KOTHLIS(SpaceRegion.MIDRIM),
    LANNIK(SpaceRegion.MIDRIM),
    MANDELL(SpaceRegion.MIDRIM),
    MANDALORE(SpaceRegion.MIDRIM),
    MOONUS(SpaceRegion.MIDRIM),
    NABOO(SpaceRegion.MIDRIM),
    ORD_MANTELL(SpaceRegion.MIDRIM),
    RIFLOR(SpaceRegion.MIDRIM),
    RODIA(SpaceRegion.MIDRIM),
    SNEEVE(SpaceRegion.MIDRIM),
    THOLATIN(SpaceRegion.MIDRIM),
    TOROLIS(SpaceRegion.MIDRIM),
    TOYDARIA(SpaceRegion.MIDRIM),
    UMGUL(SpaceRegion.MIDRIM),
    VARL(SpaceRegion.MIDRIM),
    VORTEX(SpaceRegion.MIDRIM),

    //Outer Rim 72 total
    ADUBA_III(SpaceRegion.OUTERRIM),
    ADUMAR(SpaceRegion.OUTERRIM),
    AGAMAR(SpaceRegion.OUTERRIM),
    AMMUUD(SpaceRegion.OUTERRIM),
    ASMERU(SpaceRegion.OUTERRIM),
    BAKURA(SpaceRegion.OUTERRIM),
    BANDOMEER(SpaceRegion.OUTERRIM),
    BARAB_I(SpaceRegion.OUTERRIM),
    BASTION(SpaceRegion.OUTERRIM),
    BELKADAN(SpaceRegion.OUTERRIM),
    BESPIN(SpaceRegion.OUTERRIM),
    BIMMIEL(SpaceRegion.OUTERRIM),
    BONADAN(SpaceRegion.OUTERRIM),
    BPFASSH(SpaceRegion.OUTERRIM),
    CADOMAI(SpaceRegion.OUTERRIM),
    CLAK_DOR_VII(SpaceRegion.OUTERRIM),
    CRON_DRIFT(SpaceRegion.OUTERRIM),
    DA_SOOCHA_V(SpaceRegion.OUTERRIM),
    DAGOBAH(SpaceRegion.OUTERRIM),
    DANTOOINE(SpaceRegion.OUTERRIM),
    DATHOMIR(SpaceRegion.OUTERRIM),
    DELLALT(SpaceRegion.OUTERRIM),
    DORVALLA(SpaceRegion.OUTERRIM),
    DUBRILLION(SpaceRegion.OUTERRIM),
    ENDOR(SpaceRegion.OUTERRIM),
    ERIADU(SpaceRegion.OUTERRIM),
    FIRRERRE(SpaceRegion.OUTERRIM),
    GALA(SpaceRegion.OUTERRIM),
    GAMORR(SpaceRegion.OUTERRIM),
    GARQI(SpaceRegion.OUTERRIM),
    GEONOSIS(SpaceRegion.OUTERRIM),
    HELSKA(SpaceRegion.OUTERRIM),
    HONOGHR(SpaceRegion.OUTERRIM),
    HOTH(SpaceRegion.OUTERRIM),
    ISON(SpaceRegion.OUTERRIM),
    KAMINO(SpaceRegion.OUTERRIM),
    KARFEDDION(SpaceRegion.OUTERRIM),
    KEGAN(SpaceRegion.OUTERRIM),
    KESSEL(SpaceRegion.OUTERRIM),
    KORRIBAN(SpaceRegion.OUTERRIM),
    KUBINDI(SpaceRegion.OUTERRIM),
    LIANNA(SpaceRegion.OUTERRIM),
    LWHEKK(SpaceRegion.OUTERRIM),
    MON_CALAMARI(SpaceRegion.OUTERRIM),
    MONTU_CORDU(SpaceRegion.OUTERRIM),
    MUUNILINST(SpaceRegion.OUTERRIM),
    NAR_SHADDAA(SpaceRegion.OUTERRIM),
    ORD_RADAMA(SpaceRegion.OUTERRIM),
    OSSUS(SpaceRegion.OUTERRIM),
    PRAESITLYN(SpaceRegion.OUTERRIM),
    PZOB(SpaceRegion.OUTERRIM),
    QUERMIA(SpaceRegion.OUTERRIM),
    ROON(SpaceRegion.OUTERRIM),
    RUTAN(SpaceRegion.OUTERRIM),
    RYLOTH(SpaceRegion.OUTERRIM),
    SERNPIDAL(SpaceRegion.OUTERRIM),
    SLUIS_VAN(SpaceRegion.OUTERRIM),
    SULLUST(SpaceRegion.OUTERRIM),
    SUMP(SpaceRegion.OUTERRIM),
    TATOOINE(SpaceRegion.OUTERRIM),
    TELOS(SpaceRegion.OUTERRIM),
    TOPRAWA(SpaceRegion.OUTERRIM),
    TUND(SpaceRegion.OUTERRIM),
    VARONAT(SpaceRegion.OUTERRIM),
    VERGESSO_ASTEROIDS(SpaceRegion.OUTERRIM),
    WAYLAND(SpaceRegion.OUTERRIM),
    XAGOBAH(SpaceRegion.OUTERRIM),
    YAGA_MINOR(SpaceRegion.OUTERRIM),
    YAVIN(SpaceRegion.OUTERRIM),
    YLESIA(SpaceRegion.OUTERRIM),
    ZHAR(SpaceRegion.OUTERRIM),
    ZONAMA_SEKOT(SpaceRegion.OUTERRIM),

    //Unkown Regions
    CSILLA(SpaceRegion.UNKNOWN),

    //Wild Space
    KALEE(SpaceRegion.WILDSPACE)
    ;

    private SpaceRegion region;

    Planet(SpaceRegion r)
    {
        this.region = r;
    }
}
